name: BLOG_WEB CI/CD

on:
  push:
    branches:
      - production

jobs:
  build-production:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Copy Iconfont
        run: cp ./icons/Iconfont.js ./node_modules/react-native-vector-icons/ && cp ./icons/Iconfont.json ./node_modules/react-native-vector-icons/glyphmaps/ && cp ./icons/Iconfont.ttf ./node_modules/react-native-vector-icons/Fonts/

      - name: Build
        run: npm run build:web
        env:
          CI: false

      - name: Deploy to Server
        uses: AEnterprise/rsync-deploy@v1.0
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
          ARGS: -avz --delete --exclude="*.pyc"
          SERVER_PORT: '22'
          FOLDER: ./build/*
          SERVER_IP: ${{ secrets.SSH_HOST }}
          USERNAME: ${{ secrets.SSH_USERNAME }}
          SERVER_DESTINATION: /var/www/blog_rn_web/
